import 'package:grocery/export.dart';


class GroceryDataService {
  static List<Category> getCategories() {
    return [
      Category(name: 'Fruits', icon: '🍎', color: Colors.red, id: '1'),
      Category(name: 'Vegetables', icon: '🥕', color: Colors.green, id: '2'),
      Category(name: 'Dairy', icon: '🥛', color: Colors.blue, id: '3'),
      Category(name: 'Meat', icon: '🍗', color: Colors.brown, id: '4'),
      Category(name: 'Bakery', icon: '🍞', color: Colors.orange, id: '5'),
      Category(name: 'Grains', icon: '🌾', color: Colors.amber, id: '6'),
      Category(name: 'Beverages', icon: '🍵', color: Colors.amber, id: '7'),
      Category(name: 'Snacks', icon: '🥜', color: Colors.amber, id: '8'),
      Category(name: 'Personal Care', icon: '🧴', color: Colors.amber, id: '8'),
    ];
  }

  List<String> get bannerImages => [
        'https://media.istockphoto.com/id/1273378551/photo/set-of-summer-fruits-and-berries-in-wooden-serving.webp?a=1&b=1&s=612x612&w=0&k=20&c=C9lAve8FYNn3ZK86yG4mH6J3Wf-k1Y-55PtLLDNmVaQ=',
        'https://media.istockphoto.com/id/1128687123/photo/shopping-bag-full-of-fresh-vegetables-and-fruits.webp?a=1&b=1&s=612x612&w=0&k=20&c=L-Zpt35Y33EigE1YdnRhozUlpppV6yYx4pQ7X5rBq30=',
        'https://media.istockphoto.com/id/479121800/photo/fresh-dairy-products.webp?a=1&b=1&s=612x612&w=0&k=20&c=kjYXSo0izbacYm8T146ydFd1ZEelY9nY57rJCh3sJDA=',
      ];

  static List<Product> getProducts() {
    return [
      Product(
        id: '1',
        name: 'Fresh Apples',
        description: 'Crisp and sweet red apples',
        price: 120.0,
        image: '🍎', // Keep as fallback
        imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=400&fit=crop',
        category: 'Fruits',
        unit: 'per kg',
        isOrganic: true,
        rating: 4.5,
        reviews: 128,
        tags: ['fresh', 'organic', 'healthy'],
      ),
      Product(
        id: '2',
        name: 'Bananas',
        description: 'Fresh yellow bananas',
        price: 60.0,
        image: '🍌',
        imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop',
        category: 'Fruits',
        unit: 'per dozen',
        isOrganic: false,
        rating: 4.3,
        reviews: 95,
        tags: ['fresh', 'sweet'],
      ),
      Product(
        id: '3',
        name: 'Organic Milk',
        description: 'Fresh organic whole milk',
        price: 65.0,
        image: '🥛',
        imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop',
        category: 'Dairy',
        unit: 'per liter',
        isOrganic: true,
        rating: 4.7,
        reviews: 203,
        tags: ['organic', 'dairy', 'fresh'],
      ),
      Product(
        id: '4',
        name: 'Whole Wheat Bread',
        description: 'Freshly baked whole wheat bread',
        price: 45.0,
        image: '🍞',
        imageUrl: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=400&h=400&fit=crop',
        category: 'Bakery',
        unit: 'per loaf',
        isOrganic: true,
        rating: 4.4,
        reviews: 87,
        tags: ['fresh', 'organic', 'bakery'],
      ),
      Product(
        id: '5',
        name: 'Fresh Tomatoes',
        description: 'Juicy red tomatoes',
        price: 40.0,
        image: '🍅',
        imageUrl: 'https://cdn.pixabay.com/photo/2022/09/05/09/50/tomatoes-7433786_640.jpg',
        category: 'Vegetables',
        unit: 'per kg',
        isOrganic: false,
        rating: 4.2,
        reviews: 156,
        tags: ['fresh', 'vegetables'],
      ),
      Product(
        id: '6',
        name: 'Chicken Breast',
        description: 'Fresh boneless chicken breast',
        price: 280.0,
        image: '🍗',
        imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
        category: 'Meat',
        unit: 'per kg',
        isOrganic: false,
        rating: 4.6,
        reviews: 74,
        tags: ['fresh', 'protein', 'meat'],
      ),
      Product(
        id: '7',
        name: 'Basmati Rice',
        description: 'Premium quality basmati rice',
        price: 150.0,
        image: '🍚',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW1qimQoBr7uKDwhoE2YW4OvJgtL2Z0LObBw&s',
        category: 'Grains',
        unit: 'per kg',
        isOrganic: true,
        rating: 4.8,
        reviews: 234,
        tags: ['premium', 'organic', 'grains'],
      ),
      Product(
        id: '8',
        name: 'Fresh Carrots',
        description: 'Crunchy orange carrots',
        price: 35.0,
        image: '🥕',
        imageUrl: 'https://images.unsplash.com/photo-1447175008436-054170c2e979?w=400&h=400&fit=crop',
        category: 'Vegetables',
        unit: 'per kg',
        isOrganic: true,
        rating: 4.1,
        reviews: 112,
        tags: ['fresh', 'organic', 'vegetables'],
      ),

      // Dairy
      Product(
        id: '9',
        name: 'Full Cream Milk',
        category: 'Dairy',
        price: 28.0,
        unit: 'per 500ml',
        image: '🥛',
        description: 'Fresh full cream milk from local dairy farms',
        rating: 4.7,
        reviews: 245,
        tags: ['Fresh', 'Full Cream', 'Local'],
        imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop',
      ),
      Product(
        id: '10',
        name: 'Greek Yogurt',
        category: 'Dairy',
        price: 85.0,
        unit: 'per 200g',
        image: '🥨',
        description: 'Thick and creamy Greek yogurt with probiotics',
        rating: 4.5,
        reviews: 87,
        tags: ['Probiotics', 'Creamy', 'Healthy'],
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2P6eY1qOYgcjNCbRquUa-MJKTHmFHPNxRbA&s',
      ),
      Product(
        id: '11',
        name: 'Paneer',
        category: 'Dairy',
        price: 320.0,
        unit: 'per kg',
        image: '🧀',
        description: 'Fresh homemade paneer, soft and delicious',
        rating: 4.6,
        reviews: 156,
        tags: ['Fresh', 'Homemade', 'Protein'],
        imageUrl:
            'https://media.istockphoto.com/id/1183707972/photo/paneer-cottage-cheese-close-up.webp?a=1&b=1&s=612x612&w=0&k=20&c=JS5DQNi9_Fi0gYCM_gLa6afnxJGnghbvK-wC28Ql3iM=',
      ),

// Bakery
      Product(
        id: '12',
        name: 'White Bread',
        category: 'Bakery',
        price: 25.0,
        unit: 'per loaf',
        image: '🍞',
        description: 'Soft white bread perfect for sandwiches',
        rating: 4.2,
        reviews: 178,
        tags: ['Soft', 'Fresh', 'Daily'],
        imageUrl: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=400&h=400&fit=crop',
      ),
      Product(
        id: '13',
        name: 'Croissant',
        category: 'Bakery',
        price: 45.0,
        unit: 'per piece',
        image: '🥐',
        description: 'Buttery, flaky croissants baked fresh daily',
        rating: 4.8,
        reviews: 92,
        tags: ['Buttery', 'Flaky', 'Premium'],
        imageUrl:
            'https://media.istockphoto.com/id/1487270816/photo/freshly-baked-croissants-and-cup-of-coffee-on-table-top-view.webp?a=1&b=1&s=612x612&w=0&k=20&c=lNKfhq11xGbkAHbwPnn-F2-FW582Uf1e3q7fUSNJbEo=',
      ),

// Meat & Fish
      Product(
          id: '14',
          name: 'Fresh Chicken',
          category: 'Meat',
          price: 280.0,
          unit: 'per kg',
          image: '🍗',
          description: 'Farm fresh chicken, cleaned and cut',
          rating: 4.4,
          reviews: 134,
          tags: ['Fresh', 'Farm', 'Protein'],
          imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB9HDqWL53tlD3GyoN5WXmQcqNuLHq1GiYTA&s'),
      Product(
          id: '15',
          name: 'Salmon Fish',
          category: 'Meat',
          price: 650.0,
          unit: 'per kg',
          image: '🐟',
          description: 'Fresh Atlantic salmon, rich in Omega-3',
          rating: 4.7,
          reviews: 67,
          tags: ['Fresh', 'Omega-3', 'Premium'],
          imageUrl: 'https://cti.farziengineer.co/products/Norwegian_Salmon_Fillet_2-4d880be13937.png?auto=format&sharp=20&ixlib=react-9.3.0;'),

// Beverages
      Product(
        id: '16',
        name: 'Orange Juice',
        category: 'Beverages',
        price: 95.0,
        unit: 'per 1L',
        image: '🧃',
        description: 'Fresh squeezed orange juice with pulp',
        rating: 4.3,
        reviews: 89,
        tags: ['Fresh', 'No Sugar', 'Pulp'],
        imageUrl: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400&h=400&fit=crop',
      ),
      Product(
        id: '17',
        name: 'Green Tea',
        category: 'Beverages',
        price: 240.0,
        unit: 'per 100g',
        image: '🍵',
        description: 'Premium green tea leaves with antioxidants',
        rating: 4.6,
        reviews: 156,
        tags: ['Premium', 'Antioxidants', 'Healthy'],
        imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=400&fit=crop',
      ),

// Snacks
      Product(
        id: '18',
        name: 'Mixed Nuts',
        category: 'Snacks',
        price: 450.0,
        unit: 'per 500g',
        image: '🥜',
        description: 'Premium mix of almonds, cashews, and walnuts',
        rating: 4.5,
        reviews: 123,
        tags: ['Premium', 'Healthy', 'Mixed'],
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_PjGBgyJ5eICGnDR0amcoFYpExIPZnoY5dw&s',
      ),
      Product(
        id: '19',
        name: 'Potato Chips',
        category: 'Snacks',
        price: 35.0,
        unit: 'per pack',
        image: '🥔',
        description: 'Crispy potato chips with sea salt',
        rating: 4.1,
        reviews: 245,
        tags: ['Crispy', 'Sea Salt', 'Snack'],
        imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop',
      ),

// Personal Care
      Product(
        id: '20',
        name: 'Shampoo',
        category: 'Personal Care',
        price: 180.0,
        unit: 'per 400ml',
        image: '🧴',
        description: 'Gentle shampoo for all hair types',
        rating: 4.3,
        reviews: 167,
        tags: ['Gentle', 'All Hair Types', 'Daily Use'],
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
      ),
    ];
  }
}
